import { Router } from 'express';
import { CompanyUserRole } from '@prisma/client';
import { requireAuth } from '../middlewares/requireAuth';
import { requireRestaurantCompanyContext } from '../middlewares/requireRestaurantCompanyContext';
import { requirePlanFeature } from '../middlewares/requirePlanFeature';
import { requireRestaurantAccess } from '../middlewares/requireRestaurantAccess';
import { validate } from '../middlewares/validate';
import * as Controller from '../controllers/admin-restaurant-reservations.controller';
import { assignRestaurantTableSchema, createRestaurantReservationSchema, restaurantMetricsQuerySchema, restaurantReservationQuerySchema, restaurantReservationStatusSchema, updateRestaurantReservationSchema } from '../schemas/restaurant-reservation.schema';
const router = Router();
router.use(requireAuth, requireRestaurantCompanyContext([CompanyUserRole.OWNER, CompanyUserRole.ADMIN]), requirePlanFeature('RESTAURANT_MODULE'), requireRestaurantAccess);
router.get('/dashboard', Controller.dashboard);
router.get('/metrics', (req, res, next) => { const parsed = restaurantMetricsQuerySchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ code: 400, error: true, message: 'Rango de métricas inválido.', errors: parsed.error.flatten() }); (req as any).validatedQuery = parsed.data; return next(); }, Controller.metrics);
router.get('/reservations', (req, res, next) => { const parsed = restaurantReservationQuerySchema.safeParse(req.query); if (!parsed.success) return res.status(400).json({ code: 400, error: true, message: 'Validation failed', errors: parsed.error.flatten() }); (req as any).validatedQuery = parsed.data; return next(); }, Controller.list);
router.post('/reservations', validate(createRestaurantReservationSchema), Controller.create);
router.get('/reservations/:id', Controller.get);
router.patch('/reservations/:id', validate(updateRestaurantReservationSchema), Controller.update);
router.post('/reservations/:id/status', validate(restaurantReservationStatusSchema), Controller.status);
router.post('/reservations/:id/assign-table', validate(assignRestaurantTableSchema), Controller.assignTable);
router.post('/reservations/:id/resend-confirmation', Controller.resendConfirmation);
router.get('/reservations/:id/notifications', Controller.notificationHistory);
export default router;
