import { Router } from 'express';
import authRoutes from './auth.routes';
// import userRoutes from './user.routes';
import companyRoutes from './company.routes';
import homeRoutes from './home.routes';
import testRoutes from './test.routes';
import adminAuthRoutes from './admin-auth.routes';
import bookingRoutes from './booking.routes';
import adminServiceRoutes from './admin-service.routes';
import adminStaffRoutes from './admin-staff.routes';
import adminStaffServicesRoutes from './admin-staff-services.routes';
import adminStaffAvailabilityRoutes from './admin-staff-availability.routes';
import adminHoursRoutes from './admin-hours.routes';
import adminCategoriesRoutes from './admin-categories.routes';
import adminThemeRoutes from './admin-theme.routes';
import adminBookingRoutes from './admin-booking.routes';
import adminDashboardRoutes from './admin-dashboard.routes';
import adminCustomerRoutes from './admin-customer.routes';
import adminSuperServiceTypesRoutes from './admin-super-service-types.routes';
import adminUploadRoutes from './admin-upload.routes';
import adminImageRoutes from './admin-image.routes';
import adminCompanyRoutes from './admin-company.routes';
import adminSettingsRoutes from './admin-settings.routes';
import adminProductRequestsRoutes from './admin-product-requests.routes';
import publicUploadRoutes from './public-upload.routes';
import storageRoutes from './storage.routes';
import superAdminShopsRoutes from './super-admin-shops.routes';
import superAdminProductRequestsRoutes from './super-admin-product-requests.routes';
import superAdminBusinessPricingRoutes from './super-admin-business-pricing.routes';
import profileRoutes from './profile.routes';
import staffInviteRoutes from './staff-invite.routes';
import marketplaceRoutes from './marketplace.routes';
import reviewRoutes from './review.routes';
import adminReviewRoutes from './admin-review.routes';
import adminGroupEventRoutes from './admin-group-event.routes';
import adminGroupClassRoutes from './admin-group-class.routes';
import adminGroupBookingRoutes from './admin-group-booking.routes';
import publicGroupRoutes from './public-group.routes';
import businessSignupRoutes from './business-signup.routes';
import businessPricingRoutes from './business-pricing.routes';
import { requireAuth, requireSuperAdmin } from '../middlewares/requireAuth';
import {
    superAdminListInterestedHandler,
    superAdminExportInterestedHandler,
} from '../controllers/free-event-registration.controller';

export const router = Router();
router.use('/v1/auth', authRoutes);
router.use('/v1/auth', profileRoutes);
router.use('/business-signup', businessSignupRoutes);
router.use('/public/business-pricing', businessPricingRoutes);
// router.use('/user', userRoutes);
router.use('/company', companyRoutes);
router.use('/test', testRoutes);
router.use('/admin/auth', adminAuthRoutes);
router.use('/admin/services', adminServiceRoutes);
router.use('/admin/staff', adminStaffAvailabilityRoutes);
router.use('/admin/staff', adminStaffServicesRoutes);
router.use('/admin/staff', adminStaffRoutes);
router.use('/admin/hours', adminHoursRoutes);
router.use('/admin/theme', adminThemeRoutes);
router.use('/admin/bookings', adminBookingRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/admin/customers', adminCustomerRoutes);
router.use('/admin/uploads', adminUploadRoutes);
router.use('/admin/company', adminCompanyRoutes);
router.use('/admin/settings', adminSettingsRoutes);
router.use('/admin/product-requests', adminProductRequestsRoutes);
router.use('/uploads', adminImageRoutes);
router.use('/upload', publicUploadRoutes);
router.use('/super-admin', adminSuperServiceTypesRoutes);
router.use('/super-admin', superAdminShopsRoutes);
router.use('/super-admin', superAdminProductRequestsRoutes);
router.use('/super-admin', superAdminBusinessPricingRoutes);
router.use('/storage', storageRoutes);
router.use('/booking', bookingRoutes);
router.use('/staff', staffInviteRoutes);
router.use('/admin/categories', adminCategoriesRoutes);
router.use('/home', homeRoutes);
router.use('/marketplace', marketplaceRoutes);
router.use('/review', reviewRoutes);
router.use('/admin/reviews', adminReviewRoutes);
router.use('/admin/group/events', adminGroupEventRoutes);
router.use('/admin/group/classes', adminGroupClassRoutes);
router.use('/admin/group', adminGroupBookingRoutes);
router.use('/group', publicGroupRoutes);
router.get('/super-admin/group/events/free-registrations/interested', requireAuth, requireSuperAdmin, superAdminListInterestedHandler);
router.get('/super-admin/group/events/free-registrations/interested/export', requireAuth, requireSuperAdmin, superAdminExportInterestedHandler);
