ALTER TABLE `restaurant_audit_log`
  ADD COLUMN `target_type` VARCHAR(80) NULL,
  ADD COLUMN `target_id` VARCHAR(191) NULL,
  ADD COLUMN `previous_values` JSON NULL,
  ADD COLUMN `new_values` JSON NULL,
  ADD INDEX `restaurant_audit_target_idx`(`company_id`, `target_type`, `target_id`, `created_at`);

ALTER TABLE `restaurant_notification_log`
  DROP FOREIGN KEY `restaurant_notification_log_reservation_id_fkey`,
  MODIFY COLUMN `reservation_id` INTEGER NULL,
  ADD COLUMN `waitlist_id` INTEGER NULL AFTER `reservation_id`,
  ADD COLUMN `dedup_claim_key` VARCHAR(512) NULL,
  MODIFY COLUMN `event` ENUM(
    'RESTAURANT_RESERVATION_CREATED',
    'RESTAURANT_RESERVATION_CONFIRMED',
    'RESTAURANT_RESERVATION_UPDATED',
    'RESTAURANT_RESERVATION_CANCELLED',
    'RESTAURANT_RESERVATION_REMINDER',
    'WAITLIST_ADDED',
    'WAITLIST_TABLE_READY',
    'WAITLIST_UPDATED',
    'WAITLIST_CANCELLED',
    'DEPOSIT_REQUIRED',
    'DEPOSIT_PROOF_SUBMITTED',
    'DEPOSIT_APPROVED',
    'DEPOSIT_REJECTED',
    'DEPOSIT_DEADLINE_REMINDER',
    'DEPOSIT_EXPIRED',
    'DEPOSIT_REFUNDED'
  ) NOT NULL,
  ADD UNIQUE INDEX `restaurant_notification_log_dedup_claim_key_key`(`dedup_claim_key`),
  ADD INDEX `restaurant_notification_log_waitlist_event_idx`(`company_id`, `waitlist_id`, `event`),
  ADD CONSTRAINT `restaurant_notification_log_reservation_id_fkey` FOREIGN KEY (`reservation_id`) REFERENCES `restaurant_reservation`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE `restaurant_visit` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `reservation_id` INTEGER NULL,
  `shift_id` INTEGER NULL,
  `table_id` INTEGER NULL,
  `combination_session_id` INTEGER NULL,
  `primary_waiter_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `primary_waiter_name` VARCHAR(160) NULL,
  `dining_area_snapshot` VARCHAR(120) NULL,
  `table_name_snapshot` VARCHAR(120) NULL,
  `shift_name_snapshot` VARCHAR(160) NULL,
  `guest_count` INTEGER NOT NULL,
  `subtotal_amount_cents` INTEGER NOT NULL DEFAULT 0,
  `discount_amount_cents` INTEGER NOT NULL DEFAULT 0,
  `tip_amount_cents` INTEGER NOT NULL DEFAULT 0,
  `total_paid_amount_cents` INTEGER NOT NULL DEFAULT 0,
  `currency` VARCHAR(3) NOT NULL,
  `payment_method` ENUM('CASH', 'CARD', 'QR', 'TRANSFER', 'MIXED', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `mixed_payment_breakdown` JSON NULL,
  `pos_reference` VARCHAR(160) NULL,
  `closing_notes` TEXT NULL,
  `status` ENUM('DRAFT', 'CLOSED', 'REOPENED') NOT NULL DEFAULT 'DRAFT',
  `closed_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `closed_at` DATETIME(3) NULL,
  `reopened_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `reopened_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `restaurant_visit_reservation_id_key`(`reservation_id`),
  INDEX `restaurant_visit_company_closed_at_idx`(`company_id`, `closed_at`),
  INDEX `restaurant_visit_company_shift_closed_idx`(`company_id`, `shift_id`, `closed_at`),
  INDEX `restaurant_visit_company_waiter_closed_idx`(`company_id`, `primary_waiter_user_id`, `closed_at`),
  INDEX `restaurant_visit_company_table_closed_idx`(`company_id`, `table_id`, `closed_at`),
  INDEX `restaurant_visit_company_payment_closed_idx`(`company_id`, `payment_method`, `closed_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_visit_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_visit_reservation_id_fkey` FOREIGN KEY (`reservation_id`) REFERENCES `restaurant_reservation`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_visit_shift_id_fkey` FOREIGN KEY (`shift_id`) REFERENCES `restaurant_shift`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_visit_table_id_fkey` FOREIGN KEY (`table_id`) REFERENCES `restaurant_table`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_visit_combination_session_id_fkey` FOREIGN KEY (`combination_session_id`) REFERENCES `restaurant_table_combination_session`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_visit_primary_waiter_user_id_fkey` FOREIGN KEY (`primary_waiter_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_visit_closed_by_user_id_fkey` FOREIGN KEY (`closed_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_visit_reopened_by_user_id_fkey` FOREIGN KEY (`reopened_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `restaurant_waitlist` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `guest_name` VARCHAR(160) NOT NULL,
  `phone` VARCHAR(32) NULL,
  `email` VARCHAR(255) NULL,
  `customer_profile_id` INTEGER NULL,
  `party_size` INTEGER NOT NULL,
  `preferred_dining_area_id` INTEGER NULL,
  `accessibility_notes` VARCHAR(1000) NULL,
  `seating_notes` VARCHAR(1000) NULL,
  `arrival_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `estimated_wait_minutes` INTEGER NOT NULL DEFAULT 30,
  `quoted_ready_at` DATETIME(3) NULL,
  `actual_ready_at` DATETIME(3) NULL,
  `notified_at` DATETIME(3) NULL,
  `seated_at` DATETIME(3) NULL,
  `left_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `linked_reservation_id` INTEGER NULL,
  `linked_visit_id` INTEGER NULL,
  `assigned_table_id` INTEGER NULL,
  `assigned_combination_id` INTEGER NULL,
  `source` ENUM('WALK_IN', 'PHONE', 'WHATSAPP', 'OTHER') NOT NULL DEFAULT 'WALK_IN',
  `status` ENUM('WAITING', 'NOTIFIED', 'ARRIVED', 'SEATED', 'LEFT', 'CANCELLED') NOT NULL DEFAULT 'WAITING',
  `priority` INTEGER NOT NULL DEFAULT 0,
  `manual_order` INTEGER NOT NULL DEFAULT 0,
  `internal_notes` TEXT NULL,
  `created_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `updated_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `restaurant_waitlist_linked_reservation_id_key`(`linked_reservation_id`),
  UNIQUE INDEX `restaurant_waitlist_linked_visit_id_key`(`linked_visit_id`),
  INDEX `restaurant_waitlist_company_queue_idx`(`company_id`, `status`, `manual_order`, `arrival_time`),
  INDEX `restaurant_waitlist_company_area_status_idx`(`company_id`, `preferred_dining_area_id`, `status`),
  INDEX `restaurant_waitlist_company_created_idx`(`company_id`, `created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_waitlist_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_customer_profile_id_fkey` FOREIGN KEY (`customer_profile_id`) REFERENCES `customer_profile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_preferred_dining_area_id_fkey` FOREIGN KEY (`preferred_dining_area_id`) REFERENCES `restaurant_dining_area`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_linked_reservation_id_fkey` FOREIGN KEY (`linked_reservation_id`) REFERENCES `restaurant_reservation`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_linked_visit_id_fkey` FOREIGN KEY (`linked_visit_id`) REFERENCES `restaurant_visit`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_assigned_table_id_fkey` FOREIGN KEY (`assigned_table_id`) REFERENCES `restaurant_table`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_assigned_combination_id_fkey` FOREIGN KEY (`assigned_combination_id`) REFERENCES `restaurant_table_combination`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_created_by_user_id_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_updated_by_user_id_fkey` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

ALTER TABLE `restaurant_notification_log`
  ADD CONSTRAINT `restaurant_notification_log_waitlist_id_fkey` FOREIGN KEY (`waitlist_id`) REFERENCES `restaurant_waitlist`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE `restaurant_waitlist_event` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `waitlist_id` INTEGER NOT NULL,
  `event` VARCHAR(80) NOT NULL,
  `from_status` ENUM('WAITING', 'NOTIFIED', 'ARRIVED', 'SEATED', 'LEFT', 'CANCELLED') NULL,
  `to_status` ENUM('WAITING', 'NOTIFIED', 'ARRIVED', 'SEATED', 'LEFT', 'CANCELLED') NULL,
  `actor_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `restaurant_waitlist_event_history_idx`(`company_id`, `waitlist_id`, `created_at`),
  INDEX `restaurant_waitlist_event_company_created_idx`(`company_id`, `created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_waitlist_event_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_event_waitlist_id_fkey` FOREIGN KEY (`waitlist_id`) REFERENCES `restaurant_waitlist`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `restaurant_waitlist_event_actor_user_id_fkey` FOREIGN KEY (`actor_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `restaurant_reservation_deposit` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `reservation_id` INTEGER NOT NULL,
  `required_amount_cents` INTEGER NOT NULL,
  `currency` VARCHAR(3) NOT NULL,
  `mode` ENUM('PER_PERSON', 'PER_TABLE') NOT NULL,
  `status` ENUM('REQUIRED', 'PENDING', 'PROOF_SUBMITTED', 'APPROVED', 'REJECTED', 'WAIVED', 'PARTIALLY_REFUNDED', 'REFUNDED', 'EXPIRED') NOT NULL DEFAULT 'REQUIRED',
  `payment_method` ENUM('CASH', 'CARD', 'QR', 'TRANSFER', 'OTHER') NULL,
  `payment_deadline` DATETIME(3) NULL,
  `proof_path` VARCHAR(512) NULL,
  `proof_original_name` VARCHAR(255) NULL,
  `proof_mime_type` VARCHAR(100) NULL,
  `proof_size_bytes` INTEGER NULL,
  `proof_sha256` VARCHAR(128) NULL,
  `proof_submitted_at` DATETIME(3) NULL,
  `submitted_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `public_submission_id` VARCHAR(128) NULL,
  `reviewed_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `reviewed_at` DATETIME(3) NULL,
  `rejection_reason` VARCHAR(500) NULL,
  `approved_at` DATETIME(3) NULL,
  `refunded_amount_cents` INTEGER NOT NULL DEFAULT 0,
  `refunded_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `refunded_at` DATETIME(3) NULL,
  `refund_reason` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `restaurant_reservation_deposit_reservation_id_key`(`reservation_id`),
  INDEX `restaurant_deposit_company_status_deadline_idx`(`company_id`, `status`, `payment_deadline`),
  INDEX `restaurant_deposit_company_reservation_idx`(`company_id`, `reservation_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_deposit_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_deposit_reservation_id_fkey` FOREIGN KEY (`reservation_id`) REFERENCES `restaurant_reservation`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `restaurant_deposit_submitted_by_user_id_fkey` FOREIGN KEY (`submitted_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_deposit_reviewed_by_user_id_fkey` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_deposit_refunded_by_user_id_fkey` FOREIGN KEY (`refunded_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `restaurant_customer_profile` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `customer_profile_id` INTEGER NOT NULL,
  `vip` BOOLEAN NOT NULL DEFAULT false,
  `vip_level` VARCHAR(40) NULL,
  `birthday` DATE NULL,
  `anniversary` DATE NULL,
  `preferred_dining_area_id` INTEGER NULL,
  `preferred_table_id` INTEGER NULL,
  `preferred_waiter_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `seating_preference` VARCHAR(500) NULL,
  `accessibility_requirements` VARCHAR(1000) NULL,
  `dietary_preferences` VARCHAR(1000) NULL,
  `allergies` VARCHAR(1000) NULL,
  `favorite_items` JSON NULL,
  `customer_facing_notes` VARCHAR(1000) NULL,
  `internal_hospitality_notes` TEXT NULL,
  `tags` JSON NULL,
  `last_visit_at` DATETIME(3) NULL,
  `visit_count` INTEGER NOT NULL DEFAULT 0,
  `no_show_count` INTEGER NOT NULL DEFAULT 0,
  `cancellation_count` INTEGER NOT NULL DEFAULT 0,
  `total_spend_cents` INTEGER NOT NULL DEFAULT 0,
  `average_spend_cents` INTEGER NOT NULL DEFAULT 0,
  `average_party_size` DECIMAL(8, 2) NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `restaurant_customer_profile_customer_profile_id_key`(`customer_profile_id`),
  INDEX `restaurant_customer_profile_company_vip_idx`(`company_id`, `vip`, `updated_at`),
  INDEX `restaurant_customer_profile_company_last_visit_idx`(`company_id`, `last_visit_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_customer_profile_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_customer_profile_customer_profile_id_fkey` FOREIGN KEY (`customer_profile_id`) REFERENCES `customer_profile`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `restaurant_customer_profile_preferred_dining_area_id_fkey` FOREIGN KEY (`preferred_dining_area_id`) REFERENCES `restaurant_dining_area`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_customer_profile_preferred_table_id_fkey` FOREIGN KEY (`preferred_table_id`) REFERENCES `restaurant_table`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_customer_profile_preferred_waiter_user_id_fkey` FOREIGN KEY (`preferred_waiter_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `restaurant_shift_closeout` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `shift_id` INTEGER NOT NULL,
  `status` ENUM('PREVIEWED', 'CLOSED', 'FINALIZED', 'REOPENED') NOT NULL DEFAULT 'PREVIEWED',
  `closed_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `closed_at` DATETIME(3) NULL,
  `reopened_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `reopened_at` DATETIME(3) NULL,
  `finalized_at` DATETIME(3) NULL,
  `manager_notes` TEXT NULL,
  `operational_issues` TEXT NULL,
  `reservations_summary` JSON NULL,
  `walk_in_summary` JSON NULL,
  `waitlist_summary` JSON NULL,
  `guest_summary` JSON NULL,
  `revenue_summary` JSON NULL,
  `tip_summary` JSON NULL,
  `discount_summary` JSON NULL,
  `table_turn_summary` JSON NULL,
  `dining_duration_summary` JSON NULL,
  `wait_time_summary` JSON NULL,
  `no_show_summary` JSON NULL,
  `cancellation_summary` JSON NULL,
  `missing_data_warnings` JSON NULL,
  `waiter_performance_snapshots` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `restaurant_shift_closeout_shift_id_key`(`shift_id`),
  INDEX `restaurant_closeout_company_status_idx`(`company_id`, `status`, `created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_closeout_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_closeout_shift_id_fkey` FOREIGN KEY (`shift_id`) REFERENCES `restaurant_shift`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `restaurant_closeout_closed_by_user_id_fkey` FOREIGN KEY (`closed_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_closeout_reopened_by_user_id_fkey` FOREIGN KEY (`reopened_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `restaurant_shift_closeout_adjustment` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `closeout_id` INTEGER NOT NULL,
  `actor_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `previous_snapshot` JSON NOT NULL,
  `adjusted_snapshot` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `restaurant_closeout_adjustment_history_idx`(`company_id`, `closeout_id`, `created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_closeout_adjustment_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_closeout_adjustment_closeout_id_fkey` FOREIGN KEY (`closeout_id`) REFERENCES `restaurant_shift_closeout`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `restaurant_closeout_adjustment_actor_user_id_fkey` FOREIGN KEY (`actor_user_id`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);
