import { Response } from 'express';
import { RestaurantTableOperationalStatus } from '@prisma/client';
import { AuthenticatedRequest } from '../middlewares/requireAuth';
import * as FloorService from '../services/restaurant-floor.service';

function companyId(req: AuthenticatedRequest, res: Response): number | null { const value = (req as any).companyID as number | undefined; if (!value) { res.status(400).json({ code: 400, error: true, message: 'No encontramos el contexto de la empresa.' }); return null; } return value; }
function actor(req: AuthenticatedRequest, res: Response): string | null { const value = req.authUser?.id as string | undefined; if (!value) { res.status(401).json({ code: 401, error: true, message: 'Sesión no válida.' }); return null; } return value; }
function id(value: string | string[] | undefined): number | null { const parsed = Number(Array.isArray(value) ? value[0] : value); return Number.isInteger(parsed) && parsed > 0 ? parsed : null; }
async function respond(res: Response, result: Promise<{ code: number } & Record<string, any>>) { const payload = await result; return res.status(payload.code).json(payload); }

export async function floor(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (!cid) return; const query = (req as any).validatedQuery || {}; return respond(res, FloorService.getFloor(cid, query.at, query.shiftId)); }
export async function alternatives(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), reservationId = id(req.params.id); if (!cid) return; if (!reservationId) return res.status(400).json({ code: 400, error: true, message: 'ID de reserva inválido.' }); return respond(res, FloorService.alternatives(cid, reservationId, (req as any).validatedQuery?.at)); }
export async function relocate(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), reservationId = id(req.params.id); if (!cid || !uid) return; if (!reservationId) return res.status(400).json({ code: 400, error: true, message: 'ID de reserva inválido.' }); return respond(res, FloorService.relocate(cid, reservationId, uid, (req as any).validated)); }
export async function tableStatus(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), tableId = id(req.params.id); if (!cid || !uid) return; if (!tableId) return res.status(400).json({ code: 400, error: true, message: 'ID de mesa inválido.' }); const input = (req as any).validated; return respond(res, FloorService.updateTableStatus(cid, tableId, uid, input.status as RestaurantTableOperationalStatus, input.blocked_reason)); }
export async function listCombinations(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, FloorService.listCombinations(cid)); }
export async function createCombination(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res); if (cid && uid) return respond(res, FloorService.createCombination(cid, uid, (req as any).validated)); }
export async function deleteCombination(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), combinationId = id(req.params.id); if (!cid || !uid) return; if (!combinationId) return res.status(400).json({ code: 400, error: true, message: 'ID de combinación inválido.' }); return respond(res, FloorService.deleteCombination(cid, combinationId, uid)); }
export async function releaseCombination(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), sessionId = id(req.params.id); if (!cid || !uid) return; if (!sessionId) return res.status(400).json({ code: 400, error: true, message: 'ID de sesión inválido.' }); return respond(res, FloorService.releaseCombinationSession(cid, sessionId, uid)); }
