import type { Response } from 'express';
import { AuthenticatedRequest } from '../middlewares/requireAuth';
import * as Waitlist from '../services/restaurant-waitlist.service';
import * as Visits from '../services/restaurant-visit.service';
import * as Deposits from '../services/restaurant-deposit.service';
import * as Crm from '../services/restaurant-crm.service';
import * as Closeouts from '../services/restaurant-closeout.service';
import { StorageService } from '../services/storage.service';

function companyId(req: AuthenticatedRequest, res: Response) { const value = (req as any).companyID as number | undefined; if (!value) { res.status(400).json({ code: 400, error: true, message: 'No encontramos el contexto de la empresa.' }); return null; } return value; }
function actor(req: AuthenticatedRequest, res: Response) { const value = req.authUser?.id; if (!value) { res.status(401).json({ code: 401, error: true, message: 'Sesión no válida.' }); return null; } return value; }
function id(value: string | string[] | undefined) { const parsed = Number(Array.isArray(value) ? value[0] : value); return Number.isInteger(parsed) && parsed > 0 ? parsed : null; }
async function respond(res: Response, work: Promise<{ code: number } & Record<string, any>>) { const result = await work; return res.status(result.code).json(result); }

export async function listWaitlist(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, Waitlist.list(cid, (req as any).validatedQuery)); }
export async function addWaitlist(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res); if (cid && uid) return respond(res, Waitlist.add(cid, uid, (req as any).validated)); }
export async function updateWaitlist(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), recordId = id(req.params.id); if (!cid || !uid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de lista de espera inválido.' }); return respond(res, Waitlist.update(cid, uid, recordId, (req as any).validated)); }
export async function waitlistRecommendations(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, Waitlist.recommendations(cid, (req as any).validatedQuery)); }
export async function seatWaitlist(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), recordId = id(req.params.id); if (!cid || !uid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de lista de espera inválido.' }); return respond(res, Waitlist.seat(cid, uid, recordId, (req as any).validated)); }

export async function listVisits(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, Visits.listVisits(cid, (req as any).validatedQuery)); }
export async function saveVisit(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res); if (cid && uid) return respond(res, Visits.saveVisit(cid, uid, (req as any).validated)); }
export async function saveStaffVisit(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res); if (cid && uid) return respond(res, Visits.saveVisit(cid, uid, (req as any).validated, true)); }
export async function getVisit(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), recordId = id(req.params.id); if (!cid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de visita inválido.' }); return respond(res, Visits.getVisit(cid, recordId)); }
export async function reopenVisit(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), recordId = id(req.params.id); if (!cid || !uid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de visita inválido.' }); return respond(res, Visits.reopenVisit(cid, recordId, uid, (req as any).validated.reason)); }
export async function financialMetrics(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, Visits.financialMetrics(cid, (req as any).validatedQuery)); }

export async function listDeposits(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, Deposits.listDeposits(cid, (req as any).validatedQuery)); }
export async function getDeposit(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), recordId = id(req.params.id); if (!cid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de depósito inválido.' }); return respond(res, Deposits.getDeposit(cid, recordId)); }
export async function depositProof(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), recordId = id(req.params.id); if (!cid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de depósito inválido.' }); const proof = await Deposits.privateProofPath(cid, recordId); if (!proof) return res.status(404).json({ code: 404, error: true, message: 'No encontramos el comprobante.' }); try { const fullPath = await StorageService.getFilePath(proof.path); res.set({ 'Content-Type': proof.mimeType, 'Content-Disposition': `inline; filename="${proof.originalName.replace(/[^A-Za-z0-9._-]/g, '_')}"`, 'Cache-Control': 'private, no-store' }); return res.sendFile(fullPath); } catch { return res.status(404).json({ code: 404, error: true, message: 'No encontramos el comprobante.' }); } }
export async function reviewDeposit(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), recordId = id(req.params.id); if (!cid || !uid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de depósito inválido.' }); return respond(res, Deposits.reviewDeposit(cid, recordId, uid, (req as any).validated)); }
export async function remindDeposit(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), recordId = id(req.params.id); if (!cid || !uid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de depósito inválido.' }); return respond(res, Deposits.sendDeadlineReminder(cid, recordId, uid)); }

export async function listCrm(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, Crm.list(cid, (req as any).validatedQuery)); }
export async function getCrm(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), recordId = id(req.params.customerProfileId); if (!cid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de cliente inválido.' }); return respond(res, Crm.get(cid, recordId)); }
export async function updateCrm(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), recordId = id(req.params.customerProfileId); if (!cid || !uid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de cliente inválido.' }); return respond(res, Crm.update(cid, uid, recordId, (req as any).validated)); }
export async function recalculateCrm(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), recordId = id(req.params.customerProfileId); if (!cid) return; if (!recordId) return res.status(400).json({ code: 400, error: true, message: 'ID de cliente inválido.' }); return respond(res, Crm.recalculate(cid, recordId)); }

export async function listCloseouts(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res); if (cid) return respond(res, Closeouts.list(cid, (req as any).validatedQuery)); }
export async function previewCloseout(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), shiftId = id(req.params.shiftId); if (!cid) return; if (!shiftId) return res.status(400).json({ code: 400, error: true, message: 'ID de turno inválido.' }); return respond(res, Closeouts.preview(cid, shiftId)); }
export async function closeCloseout(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), shiftId = id(req.params.shiftId); if (!cid || !uid) return; if (!shiftId) return res.status(400).json({ code: 400, error: true, message: 'ID de turno inválido.' }); return respond(res, Closeouts.close(cid, shiftId, uid, (req as any).validated)); }
export async function finalizeCloseout(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), shiftId = id(req.params.shiftId); if (!cid || !uid) return; if (!shiftId) return res.status(400).json({ code: 400, error: true, message: 'ID de turno inválido.' }); return respond(res, Closeouts.finalize(cid, shiftId, uid)); }
export async function reopenCloseout(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), shiftId = id(req.params.shiftId); if (!cid || !uid) return; if (!shiftId) return res.status(400).json({ code: 400, error: true, message: 'ID de turno inválido.' }); return respond(res, Closeouts.reopen(cid, shiftId, uid, (req as any).validated.reason)); }
export async function adjustCloseout(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), uid = actor(req, res), shiftId = id(req.params.shiftId); if (!cid || !uid) return; if (!shiftId) return res.status(400).json({ code: 400, error: true, message: 'ID de turno inválido.' }); return respond(res, Closeouts.adjust(cid, shiftId, uid, (req as any).validated)); }
export async function getCloseout(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), shiftId = id(req.params.shiftId); if (!cid) return; if (!shiftId) return res.status(400).json({ code: 400, error: true, message: 'ID de turno inválido.' }); return respond(res, Closeouts.get(cid, shiftId)); }
export async function exportCloseout(req: AuthenticatedRequest, res: Response) { const cid = companyId(req, res), shiftId = id(req.params.shiftId); if (!cid) return; if (!shiftId) return res.status(400).json({ code: 400, error: true, message: 'ID de turno inválido.' }); const result = await Closeouts.get(cid, shiftId); if (result.error) return res.status(result.code).json(result); const closeout: any = result.data; const rows = [['section', 'value'], ['shift', closeout.shift?.name || ''], ['status', closeout.status], ['total_paid_amount_cents', closeout.revenue_summary?.total_paid_amount_cents ?? 0], ['tip_amount_cents', closeout.tip_summary?.tip_amount_cents ?? 0], ['discount_amount_cents', closeout.discount_summary?.discount_amount_cents ?? 0], ['missing_data_warnings', JSON.stringify(closeout.missing_data_warnings || [])]]; for (const waiter of closeout.waiter_performance_snapshots || []) rows.push([`waiter:${waiter.user_id}`, JSON.stringify(waiter)]); const csv = rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'); res.set({ 'Content-Type': 'text/csv; charset=utf-8', 'Content-Disposition': `attachment; filename="restaurant-closeout-${shiftId}.csv"` }); return res.status(200).send(csv); }
