CREATE TABLE `restaurant_reservation` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `company_id` INTEGER NOT NULL,
  `customer_profile_id` INTEGER NULL,
  `table_id` INTEGER NULL,
  `reservation_code` VARCHAR(48) NOT NULL,
  `reservation_date` DATETIME(3) NOT NULL,
  `start_time` DATETIME(3) NOT NULL,
  `end_time` DATETIME(3) NOT NULL,
  `party_size` INTEGER NOT NULL,
  `customer_name` VARCHAR(160) NOT NULL,
  `customer_phone` VARCHAR(32) NULL,
  `customer_email` VARCHAR(255) NULL,
  `notes` TEXT NULL,
  `internal_notes` TEXT NULL,
  `status` ENUM('PENDING', 'CONFIRMED', 'ARRIVED', 'SEATED', 'COMPLETED', 'CANCELLED', 'NO_SHOW') NOT NULL DEFAULT 'PENDING',
  `source` ENUM('ONLINE', 'ADMIN', 'PHONE', 'WHATSAPP', 'WALK_IN') NOT NULL DEFAULT 'ADMIN',
  `seated_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `cancellation_reason` VARCHAR(500) NULL,
  `created_by_user_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `restaurant_reservation_reservation_code_key`(`reservation_code`),
  INDEX `restaurant_reservation_company_date_idx`(`company_id`, `reservation_date`),
  INDEX `restaurant_reservation_company_status_idx`(`company_id`, `status`),
  INDEX `restaurant_reservation_company_source_idx`(`company_id`, `source`),
  INDEX `restaurant_reservation_table_time_idx`(`table_id`, `start_time`, `end_time`),
  PRIMARY KEY (`id`),
  CONSTRAINT `restaurant_reservation_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `company`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `restaurant_reservation_customer_profile_id_fkey` FOREIGN KEY (`customer_profile_id`) REFERENCES `customer_profile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_reservation_table_id_fkey` FOREIGN KEY (`table_id`) REFERENCES `restaurant_table`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `restaurant_reservation_created_by_user_id_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);
